########### Copyright 2023, NatterNet
## Written by Muhammet Arslan <muhammet.arsln@gmail.com>, August 2023
#########
version: "3.2"
services:
  natternet-nats:
    container_name: natternet-nats-jetstream-server
    hostname: nats-jetstream-server
    image: "nats:latest"
    command: "--debug -js -sd /data"
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - natternet
    volumes:
      - ./jetstream-data:/data
  natternet-sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: natternet-sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - natternet
  natternet-mongo:
    image: mongo
    container_name: natternet-mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:

      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: natternet
    volumes:
      - natternet-mongo-data:/data/db
    networks:
      - natternet
  natternet-mongo-express:
    image: mongo-express
    container_name: natternet-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: natternet
      ME_CONFIG_MONGODB_URL: mongodb://root:natternet@natternet-mongo:27017/
    networks:
      - natternet

volumes:
  natternet-mongo-data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  natternet: