// Code generated by MockGen. DO NOT EDIT.
// Source: room_command_services.go

// Package mockchatdomainservices is a generated GoMock package.
package mockchatdomainservices

import (
	reflect "reflect"

	dto "github.com/iammuho/natternet/internal/chat/application/dto"
	values "github.com/iammuho/natternet/internal/chat/domain/values"
	errorhandler "github.com/iammuho/natternet/pkg/errorhandler"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomCommandDomainServices is a mock of RoomCommandDomainServices interface.
type MockRoomCommandDomainServices struct {
	ctrl     *gomock.Controller
	recorder *MockRoomCommandDomainServicesMockRecorder
}

// MockRoomCommandDomainServicesMockRecorder is the mock recorder for MockRoomCommandDomainServices.
type MockRoomCommandDomainServicesMockRecorder struct {
	mock *MockRoomCommandDomainServices
}

// NewMockRoomCommandDomainServices creates a new mock instance.
func NewMockRoomCommandDomainServices(ctrl *gomock.Controller) *MockRoomCommandDomainServices {
	mock := &MockRoomCommandDomainServices{ctrl: ctrl}
	mock.recorder = &MockRoomCommandDomainServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomCommandDomainServices) EXPECT() *MockRoomCommandDomainServicesMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomCommandDomainServices) CreateRoom(arg0 *dto.CreateRoomReqDTO) (*values.RoomValue, *errorhandler.Response) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0)
	ret0, _ := ret[0].(*values.RoomValue)
	ret1, _ := ret[1].(*errorhandler.Response)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomCommandDomainServicesMockRecorder) CreateRoom(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomCommandDomainServices)(nil).CreateRoom), arg0)
}

// JoinRoom mocks base method.
func (m *MockRoomCommandDomainServices) JoinRoom(arg0 *dto.JoinRoomReqDTO) (*values.RoomValue, *errorhandler.Response) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", arg0)
	ret0, _ := ret[0].(*values.RoomValue)
	ret1, _ := ret[1].(*errorhandler.Response)
	return ret0, ret1
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockRoomCommandDomainServicesMockRecorder) JoinRoom(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockRoomCommandDomainServices)(nil).JoinRoom), arg0)
}

// LeaveRoom mocks base method.
func (m *MockRoomCommandDomainServices) LeaveRoom(arg0 *dto.LeaveRoomReqDTO) (*values.RoomValue, *errorhandler.Response) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", arg0)
	ret0, _ := ret[0].(*values.RoomValue)
	ret1, _ := ret[1].(*errorhandler.Response)
	return ret0, ret1
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockRoomCommandDomainServicesMockRecorder) LeaveRoom(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockRoomCommandDomainServices)(nil).LeaveRoom), arg0)
}

// UpdateLastMessage mocks base method.
func (m *MockRoomCommandDomainServices) UpdateLastMessage(arg0 string, arg1 *values.MessageValue) *errorhandler.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastMessage", arg0, arg1)
	ret0, _ := ret[0].(*errorhandler.Response)
	return ret0
}

// UpdateLastMessage indicates an expected call of UpdateLastMessage.
func (mr *MockRoomCommandDomainServicesMockRecorder) UpdateLastMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastMessage", reflect.TypeOf((*MockRoomCommandDomainServices)(nil).UpdateLastMessage), arg0, arg1)
}
